version: '3'
services:
  terracost:
    image: golang:1.17.3
    volumes:
      - .:/go/src/github.com/cycloidio/terracost
      - $GOPATH/pkg/mod:/go/pkg/mod
    working_dir: /go/src/github.com/cycloidio/terracost
    networks:
      terracost-subnet:
        ipv4_address: 172.44.0.3

  database:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '33060:3306'
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=terracost
      - MYSQL_DATABASE=terracost_test
    networks:
      terracost-subnet:
        ipv4_address: 172.44.0.2

  # This service is used to wait for service to be ready
  # to accept connections, see dev-env-up target in Makefile.
  wait:
    image: dokku/wait:0.4.3
    networks:
      terracost-subnet:
        ipv4_address: 172.44.0.42

networks:
  terracost-subnet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.44.0.0/16
